//region                = "us-east-1"
//env_name              = "dev"
//source_repo           = "github.com/org/my-repo-name"
//application_name      = "my-application"
//name_prefix           = "myapp"